plugins { id 'com.android.application' }

def mapsApiKey = System.getenv('MAPS_API_KEY') ?: 'AIzaSyA-tIK8KiByozjZRT8Knvq5lbCEDiKHfP8'

android {
    namespace 'com.mdiaz.trxlauncher'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mdiaz.trxlauncher'
        minSdk 26
        targetSdk 35
        versionCode 14
        versionName '0.5.2'
        manifestPlaceholders = [MAPS_API_KEY: mapsApiKey]
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}


dependencies {
    implementation 'com.google.android.gms:play-services-maps:20.0.0'
}
