package com.mdiaz.trxlauncher;
import android.graphics.Color;import android.graphics.drawable.Drawable;import android.view.*;import android.widget.*;

final class HomeScreen extends ScrollView{
    private final MainActivity a;private LinearLayout body;
    HomeScreen(MainActivity c){super(c);a=c;setFillViewport(true);show(0);}
    private void show(int tab){removeAllViews();body=Ui.col(a);body.setPadding(Ui.dp(a,24),Ui.dp(a,18),Ui.dp(a,24),Ui.dp(a,22));addView(body);
        hero("PRECISION COMMAND","Focused on the road. Ready for everything.","Navigation, media, and vehicle data working together.");
        body.addView(Ui.tabs(a,new String[]{"Command","Drive","Quick Controls","Weather"},tab,this::show),new LinearLayout.LayoutParams(-1,Ui.dp(a,70)));
        if(tab==0)command();else if(tab==1)drive();else if(tab==2)quick();else weather();}
    private void hero(String eyebrow,String title,String sub){TextView e=Ui.text(a,eyebrow,11,Ui.RED,true);body.addView(e);TextView t=Ui.text(a,title,32,Color.WHITE,true);t.setPadding(0,6,0,2);body.addView(t);body.addView(Ui.text(a,sub,14,0xffa5a8ae,false));Space s=new Space(a);body.addView(s,new LinearLayout.LayoutParams(1,Ui.dp(a,18)));}
    private void command(){LinearLayout row=Ui.row(a);View map=routeCard();row.addView(map,new LinearLayout.LayoutParams(0,Ui.dp(a,430),2));LinearLayout right=Ui.col(a);right.setPadding(Ui.dp(a,16),0,0,0);right.addView(nowPlaying(),new LinearLayout.LayoutParams(-1,0,1));Space s=new Space(a);right.addView(s,new LinearLayout.LayoutParams(1,12));right.addView(vehicle(),new LinearLayout.LayoutParams(-1,0,1));row.addView(right,new LinearLayout.LayoutParams(0,Ui.dp(a,430),1));body.addView(row);}
    private View routeCard(){FrameLayout card=new FrameLayout(a);card.setBackgroundResource(com.mdiaz.trxlauncher.R.drawable.hero_red);card.setForeground(Ui.bg(0x77000000,0xff34373d,22,a));LinearLayout overlay=Ui.col(a);overlay.setPadding(26,24,26,24);overlay.addView(Ui.text(a,"ACTIVE ROUTE  •  LIVE TRAFFIC",12,0xff68d391,true));overlay.addView(Ui.text(a,"Where are we heading?",28,Color.WHITE,true));overlay.addView(Ui.text(a,"Tap to open the live Google navigation map",14,0xffc8cbd1,false));Space s=new Space(a);overlay.addView(s,new LinearLayout.LayoutParams(1,0,1));Button b=Ui.button(a,"OPEN LIVE MAP  ➤",true);b.setOnClickListener(v->a.openNavigation(null));overlay.addView(b,new LinearLayout.LayoutParams(-1,64));card.addView(overlay,new FrameLayout.LayoutParams(-1,-1));card.setOnClickListener(v->a.openNavigation(null));return card;}
    private View nowPlaying(){LinearLayout c=Ui.col(a);c.setPadding(18,16,18,16);c.setBackground(Ui.bg(Ui.CARD,0xff393c42,20,a));c.addView(Ui.text(a,"NOW PLAYING  •  CONNECTED",12,0xff68d391,true));c.addView(Ui.text(a,MediaAccessService.title,20,Color.WHITE,true));c.addView(Ui.text(a,MediaAccessService.artist,13,0xffa9adb4,false));Button play=Ui.button(a,"◀       ▶ / ❚❚       ▶",false);play.setOnClickListener(v->MediaAccessService.playPause());c.addView(play,new LinearLayout.LayoutParams(-1,58));return c;}
    private View vehicle(){LinearLayout c=Ui.col(a);c.setPadding(18,16,18,16);c.setBackground(Ui.bg(Ui.CARD,0xff393c42,20,a));c.addView(Ui.text(a,"LIVE VEHICLE  •  "+ObdService.status,12,ObdService.connected?0xff68d391:Ui.RED,true));LinearLayout r=Ui.row(a);r.addView(Ui.metric(a,"COOLANT",ObdService.coolant,"°F"),new LinearLayout.LayoutParams(0,-1,1));r.addView(Ui.metric(a,"BATTERY",ObdService.voltage,"V"),new LinearLayout.LayoutParams(0,-1,1));c.addView(r);return c;}
    private void drive(){body.addView(vehicle(),new LinearLayout.LayoutParams(-1,260));}
    private void quick(){String[] x={"Bluetooth","Wi‑Fi","Brightness","Do Not Disturb","Launch Camera","Media Output"};for(String s:x){Button b=Ui.button(a,s,false);body.addView(b,new LinearLayout.LayoutParams(-1,64));Ui.margins(b,0,5,0,5);}}
    private void weather(){body.addView(Ui.metric(a,"PLAINSBORO, NJ","67","°F"),new LinearLayout.LayoutParams(-1,180));}
}
