package com.mdiaz.trxlauncher;
import android.graphics.Color;import android.provider.Settings;import android.text.TextUtils;import android.widget.*;
final class MediaScreen extends ScrollView{
    private final MainActivity a;MediaScreen(MainActivity c){super(c);a=c;setFillViewport(true);show(0);}
    private void show(int tab){removeAllViews();LinearLayout root=Ui.col(a);root.setPadding(24,18,24,22);addView(root);root.addView(Ui.text(a,"PRECISION MEDIA",11,Ui.RED,true));root.addView(Ui.text(a,"Your music, perfectly centered.",32,Color.WHITE,true));root.addView(Ui.text(a,"Large controls, sources, queue, and audio tuning.",14,0xffa5a8ae,false));root.addView(Ui.tabs(a,new String[]{"Now Playing","Queue","Sources","Audio"},tab,this::show),new LinearLayout.LayoutParams(-1,76));
        if(tab==0)now(root);else if(tab==1)queue(root);else if(tab==2)sources(root);else audio(root);}
    private void now(LinearLayout r){LinearLayout c=Ui.col(a);c.setPadding(28,26,28,26);c.setBackground(Ui.bg(Ui.CARD,0xff3c3f45,22,a));c.addView(Ui.text(a,MediaAccessService.hasAccess(a)?MediaAccessService.artist.toUpperCase():"BASIC MEDIA CONTROL",13,0xffaaaeb5,true));c.addView(Ui.text(a,MediaAccessService.hasAccess(a)?MediaAccessService.title:"Metadata access optional",34,Color.WHITE,true));LinearLayout controls=Ui.row(a);Button prev=Ui.button(a,"◀",false),play=Ui.button(a,MediaAccessService.playing?"❚❚":"▶",true),next=Ui.button(a,"▶",false);prev.setOnClickListener(v->MediaAccessService.previous());play.setOnClickListener(v->MediaAccessService.playPause());next.setOnClickListener(v->MediaAccessService.next());controls.addView(prev,new LinearLayout.LayoutParams(0,84,1));controls.addView(play,new LinearLayout.LayoutParams(0,84,1));controls.addView(next,new LinearLayout.LayoutParams(0,84,1));c.addView(controls);if(!MediaAccessService.hasAccess(a)){Button optional=Ui.button(a,"OPTIONAL: SHOW ARTWORK & TRACK INFO",false);optional.setOnClickListener(v->a.requestMediaAccess());c.addView(optional,new LinearLayout.LayoutParams(-1,62));}r.addView(c,new LinearLayout.LayoutParams(-1,380));}
    private void queue(LinearLayout r){r.addView(Ui.text(a,"The active media app controls and publishes its queue.",18,Color.WHITE,false));}
    private void sources(LinearLayout r){Button y=Ui.button(a,"Open YouTube Music",true);y.setOnClickListener(v->{var i=a.getPackageManager().getLaunchIntentForPackage("com.google.android.apps.youtube.music");if(i!=null)a.startActivity(i);});r.addView(y,new LinearLayout.LayoutParams(-1,80));}
    private void audio(LinearLayout r){r.addView(Ui.text(a,"Audio output follows the connected Android device. Hardware volume remains available from the vehicle controls.",17,Color.WHITE,false));}
}
