package com.mdiaz.trxlauncher;
import android.graphics.Color;import android.provider.Settings;import android.text.TextUtils;import android.widget.*;
final class MediaScreen extends ScrollView{
    private final MainActivity a;MediaScreen(MainActivity c){super(c);a=c;setFillViewport(true);show(0);}
    private void show(int tab){removeAllViews();LinearLayout root=Ui.col(a);root.setPadding(24,18,24,22);addView(root);root.addView(Ui.text(a,"PRECISION MEDIA",11,Ui.RED,true));root.addView(Ui.text(a,"Your music, perfectly centered.",32,Color.WHITE,true));root.addView(Ui.text(a,"Large controls, sources, queue, and audio tuning.",14,0xffa5a8ae,false));root.addView(Ui.tabs(a,new String[]{"Now Playing","Queue","Sources","Audio"},tab,this::show),new LinearLayout.LayoutParams(-1,76));
        if(!MediaAccessService.hasAccess(a)){LinearLayout p=Ui.col(a);p.setPadding(26,30,26,30);p.setBackground(Ui.bg(Ui.CARD,0xff3b3e44,22,a));p.addView(Ui.text(a,"ONE-TIME MEDIA ACCESS",21,Color.WHITE,true));p.addView(Ui.text(a,"Android requires Notification Access to read and control the active MediaSession. Once enabled, TRX Launcher will reconnect automatically and will not ask again.",15,0xffb7bac0,false));Button b=Ui.button(a,"ENABLE TRX MEDIA CONTROLS",true);b.setOnClickListener(v->a.requestMediaAccess());p.addView(b,new LinearLayout.LayoutParams(-1,70));root.addView(p);return;}
        if(tab==0)now(root);else if(tab==1)queue(root);else if(tab==2)sources(root);else audio(root);}
    private void now(LinearLayout r){LinearLayout c=Ui.col(a);c.setPadding(28,26,28,26);c.setBackground(Ui.bg(Ui.CARD,0xff3c3f45,22,a));c.addView(Ui.text(a,MediaAccessService.artist.toUpperCase(),13,0xffaaaeb5,true));c.addView(Ui.text(a,MediaAccessService.title,34,Color.WHITE,true));Button controls=Ui.button(a,"◀      "+(MediaAccessService.playing?"❚❚":"▶")+"      ▶",true);controls.setOnClickListener(v->MediaAccessService.playPause());c.addView(controls,new LinearLayout.LayoutParams(-1,84));r.addView(c,new LinearLayout.LayoutParams(-1,360));}
    private void queue(LinearLayout r){r.addView(Ui.text(a,"The active media app controls and publishes its queue.",18,Color.WHITE,false));}
    private void sources(LinearLayout r){Button y=Ui.button(a,"Open YouTube Music",true);y.setOnClickListener(v->{var i=a.getPackageManager().getLaunchIntentForPackage("com.google.android.apps.youtube.music");if(i!=null)a.startActivity(i);});r.addView(y,new LinearLayout.LayoutParams(-1,80));}
    private void audio(LinearLayout r){r.addView(Ui.text(a,"Audio output follows the connected Android device. Hardware volume remains available from the vehicle controls.",17,Color.WHITE,false));}
}
