package com.mdiaz.trxlauncher;
import android.content.*;import android.media.MediaMetadata;import android.media.session.*;import android.provider.Settings;import android.service.notification.NotificationListenerService;import java.util.*;
public class MediaAccessService extends NotificationListenerService{
 static volatile String title="No active track",artist="Open a media source";static volatile boolean playing;private static volatile MediaController controller;
 @Override public void onListenerConnected(){refresh(this);}
 @Override public void onNotificationPosted(android.service.notification.StatusBarNotification n){refresh(this);}
 static boolean hasAccess(Context c){String s=Settings.Secure.getString(c.getContentResolver(),"enabled_notification_listeners");return s!=null&&s.toLowerCase().contains(c.getPackageName().toLowerCase());}
 static void refresh(Context c){if(!hasAccess(c))return;try{MediaSessionManager m=(MediaSessionManager)c.getSystemService(Context.MEDIA_SESSION_SERVICE);List<MediaController> all=m.getActiveSessions(new ComponentName(c,MediaAccessService.class));controller=null;for(MediaController x:all){controller=x;PlaybackState ps=x.getPlaybackState();if(ps!=null&&ps.getState()==PlaybackState.STATE_PLAYING)break;}if(controller==null)return;MediaMetadata md=controller.getMetadata();PlaybackState ps=controller.getPlaybackState();playing=ps!=null&&ps.getState()==PlaybackState.STATE_PLAYING;if(md!=null){String t=md.getString(MediaMetadata.METADATA_KEY_TITLE),ar=md.getString(MediaMetadata.METADATA_KEY_ARTIST);if(t!=null&&!t.isBlank())title=t;if(ar!=null&&!ar.isBlank())artist=ar;}}catch(Throwable ignored){}}
 static void playPause(){try{if(controller!=null){if(playing)controller.getTransportControls().pause();else controller.getTransportControls().play();playing=!playing;return;}}catch(Throwable ignored){}sendKey(android.view.KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE);}
 static void previous(){try{if(controller!=null){controller.getTransportControls().skipToPrevious();return;}}catch(Throwable ignored){}sendKey(android.view.KeyEvent.KEYCODE_MEDIA_PREVIOUS);}
 static void next(){try{if(controller!=null){controller.getTransportControls().skipToNext();return;}}catch(Throwable ignored){}sendKey(android.view.KeyEvent.KEYCODE_MEDIA_NEXT);}
 private static void sendKey(int code){try{Context c=AppContext.get();if(c==null)return;android.media.AudioManager m=(android.media.AudioManager)c.getSystemService(Context.AUDIO_SERVICE);long now=android.os.SystemClock.uptimeMillis();m.dispatchMediaKeyEvent(new android.view.KeyEvent(now,now,android.view.KeyEvent.ACTION_DOWN,code,0));m.dispatchMediaKeyEvent(new android.view.KeyEvent(now,now,android.view.KeyEvent.ACTION_UP,code,0));}catch(Throwable ignored){}}
}
