package com.mdiaz.trxlauncher;

import android.Manifest;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;
import com.google.android.gms.maps.GoogleMap;import com.google.android.gms.maps.OnMapReadyCallback;import com.google.android.gms.maps.model.LatLng;
import com.google.android.libraries.navigation.*;
import com.google.android.libraries.places.api.Places;import com.google.android.libraries.places.api.model.*;import com.google.android.libraries.places.api.net.*;
import java.util.*;

final class NavigationScreen extends FrameLayout{
 private final MainActivity a;private final NavigationView navView;private final FrameLayout chrome;private final LinearLayout suggestions;private final EditText search;private Navigator navigator;private GoogleMap map;private PlacesClient places;private int searchToken;private boolean guiding,navigatorLoading;
 NavigationScreen(MainActivity c,Bundle state){super(c);a=c;setBackgroundColor(Ui.BG);
  navView=new NavigationView(c);navView.onCreate(state);addView(navView,new LayoutParams(-1,-1));
  chrome=new FrameLayout(c);addView(chrome,new LayoutParams(-1,-1));
  LinearLayout top=Ui.col(c);top.setPadding(Ui.dp(c,22),Ui.dp(c,14),Ui.dp(c,22),0);chrome.addView(top,new LayoutParams(-1,-2,Gravity.TOP));
  top.addView(Ui.tabs(c,new String[]{"Route","Recents","Favorites","Map Options"},0,this::selectTab),new LinearLayout.LayoutParams(-1,Ui.dp(c,66)));
  search=new EditText(c);search.setSingleLine(true);search.setHint("Search destination or address");search.setTextColor(Color.WHITE);search.setHintTextColor(0xffa1a5ac);search.setTextSize(16);search.setPadding(22,0,22,0);search.setBackground(Ui.bg(0xf207080a,0xff565a61,18,c));top.addView(search,new LinearLayout.LayoutParams(-1,Ui.dp(c,64)));
  suggestions=Ui.col(c);suggestions.setBackground(Ui.bg(0xf508090b,Ui.RED,16,c));suggestions.setVisibility(GONE);top.addView(suggestions,new LinearLayout.LayoutParams(-1,-2));
  LinearLayout tools=Ui.col(c);String[] toolNames={"◎","2D/3D","TRAFFIC","LAYER","🔊"};for(String n:toolNames){Button b=Ui.button(c,n,false);tools.addView(b,new LinearLayout.LayoutParams(Ui.dp(c,88),Ui.dp(c,56)));if(n.equals("TRAFFIC"))b.setOnClickListener(v->{if(map!=null)map.setTrafficEnabled(!map.isTrafficEnabled());});if(n.equals("LAYER"))b.setOnClickListener(v->cycleLayer());}LayoutParams tl=new LayoutParams(Ui.dp(c,90),-2,Gravity.RIGHT|Gravity.CENTER_VERTICAL);tl.rightMargin=Ui.dp(c,18);chrome.addView(tools,tl);
  Button end=Ui.button(c,"END ROUTE",true);end.setVisibility(GONE);end.setOnClickListener(v->{if(navigator!=null)navigator.stopGuidance();guiding=false;v.setVisibility(GONE);search.setVisibility(VISIBLE);});end.setTag("end");LayoutParams el=new LayoutParams(Ui.dp(c,160),Ui.dp(c,62),Gravity.RIGHT|Gravity.BOTTOM);el.setMargins(0,0,Ui.dp(c,24),Ui.dp(c,24));chrome.addView(end,el);
  initGoogle();wireSearch();}
 private void initGoogle(){if(!Places.isInitialized())Places.initialize(a.getApplicationContext(),BuildConfig.MAPS_API_KEY);places=Places.createClient(a);navView.getMapAsync(g->{map=g;try{map.setTrafficEnabled(true);map.getUiSettings().setCompassEnabled(true);map.getUiSettings().setZoomControlsEnabled(false);}catch(SecurityException ignored){}});ensureNavigator();}
 void ensureNavigator(){if(navigator!=null||navigatorLoading||a.checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;navigatorLoading=true;NavigationApi.getNavigator(a,new NavigationApi.NavigatorListener(){public void onNavigatorReady(Navigator n){navigatorLoading=false;navigator=n;navView.setNavigationUiEnabled(true);navView.setHeaderEnabled(true);navView.setEtaCardEnabled(true);navView.setRecenterButtonEnabled(true);navView.setSpeedometerEnabled(true);navView.setSpeedLimitIconEnabled(true);}public void onError(int code){navigatorLoading=false;Toast.makeText(a,"Google Navigation unavailable ("+code+")",Toast.LENGTH_LONG).show();}});}
 private void wireSearch(){search.setImeOptions(EditorInfo.IME_ACTION_GO);search.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_GO){routeTo(search.getText().toString());return true;}return false;});search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void onTextChanged(CharSequence s,int st,int b,int c){predict(s.toString());}public void afterTextChanged(android.text.Editable e){}});}
 private void predict(String q){int token=++searchToken;suggestions.removeAllViews();if(q.trim().length()<2){suggestions.setVisibility(GONE);return;}FindAutocompletePredictionsRequest req=FindAutocompletePredictionsRequest.builder().setQuery(q).setCountries("US").build();places.findAutocompletePredictions(req).addOnSuccessListener(result->{if(token!=searchToken)return;suggestions.removeAllViews();int count=0;for(AutocompletePrediction p:result.getAutocompletePredictions()){if(count++>=6)break;String primary=p.getPrimaryText(null).toString(),secondary=p.getSecondaryText(null).toString();Button b=Ui.button(a,primary+"\n"+secondary,false);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->fetchAndRoute(p.getPlaceId(),primary));suggestions.addView(b,new LinearLayout.LayoutParams(-1,Ui.dp(a,66)));}suggestions.setVisibility(suggestions.getChildCount()>0?VISIBLE:GONE);}).addOnFailureListener(x->suggestions.setVisibility(GONE));}
 private void fetchAndRoute(String id,String title){FetchPlaceRequest req=FetchPlaceRequest.builder(id,Arrays.asList(Place.Field.ID,Place.Field.DISPLAY_NAME,Place.Field.FORMATTED_ADDRESS,Place.Field.LOCATION)).build();places.fetchPlace(req).addOnSuccessListener(r->{Place p=r.getPlace();LatLng ll=p.getLocation();if(ll!=null)startGuidance(ll,title);}).addOnFailureListener(e->Toast.makeText(a,"Destination unavailable",Toast.LENGTH_SHORT).show());}
 void routeTo(String query){if(query==null||query.isBlank()){search.requestFocus();return;}search.setText(query);FindAutocompletePredictionsRequest req=FindAutocompletePredictionsRequest.builder().setQuery(query).setCountries("US").build();places.findAutocompletePredictions(req).addOnSuccessListener(r->{if(r.getAutocompletePredictions().isEmpty())Toast.makeText(a,"No destination found",Toast.LENGTH_SHORT).show();else fetchAndRoute(r.getAutocompletePredictions().get(0).getPlaceId(),query);});}
 private void startGuidance(LatLng ll,String title){if(navigator==null){Toast.makeText(a,"Navigation is initializing",Toast.LENGTH_SHORT).show();return;}Waypoint w=new Waypoint.Builder().setLatLng(ll.latitude,ll.longitude).setTitle(title).setVehicleStopover(true).build();RoutingOptions o=new RoutingOptions();o.travelMode(RoutingOptions.TravelMode.DRIVING);navigator.setDestination(w,o).setOnResultListener(status->{if(status==Navigator.RouteStatus.OK){navigator.startGuidance();guiding=true;search.setVisibility(GONE);suggestions.setVisibility(GONE);View e=chrome.findViewWithTag("end");if(e!=null)e.setVisibility(VISIBLE);}else Toast.makeText(a,"Route unavailable: "+status,Toast.LENGTH_LONG).show();});}
 private void selectTab(int tab){if(tab==0){search.setVisibility(VISIBLE);return;}if(tab==1||tab==2){suggestions.removeAllViews();String[] rows=tab==1?new String[]{"Recent destinations appear after your first route","Home","Work"}:new String[]{"Home","Work","Add favorite"};for(String s:rows){Button b=Ui.button(a,s,false);b.setOnClickListener(v->routeTo(s));suggestions.addView(b,new LinearLayout.LayoutParams(-1,64));}suggestions.setVisibility(VISIBLE);}else showMapOptions();}
 private void showMapOptions(){suggestions.removeAllViews();String[] opts={"Road map","Satellite","Hybrid","Live traffic","Avoid tolls","Avoid highways","Avoid ferries","Day / Night / Auto"};for(String x:opts){Button b=Ui.button(a,x,false);if(x.equals("Road map"))b.setOnClickListener(v->{if(map!=null)map.setMapType(GoogleMap.MAP_TYPE_NORMAL);});if(x.equals("Satellite"))b.setOnClickListener(v->{if(map!=null)map.setMapType(GoogleMap.MAP_TYPE_SATELLITE);});if(x.equals("Hybrid"))b.setOnClickListener(v->{if(map!=null)map.setMapType(GoogleMap.MAP_TYPE_HYBRID);});if(x.equals("Live traffic"))b.setOnClickListener(v->{if(map!=null)map.setTrafficEnabled(!map.isTrafficEnabled());});suggestions.addView(b,new LinearLayout.LayoutParams(-1,60));}suggestions.setVisibility(VISIBLE);}
 private void cycleLayer(){if(map==null)return;int t=map.getMapType();map.setMapType(t==GoogleMap.MAP_TYPE_NORMAL?GoogleMap.MAP_TYPE_HYBRID:GoogleMap.MAP_TYPE_NORMAL);}
 void onStart(){navView.onStart();}void onResume(){navView.onResume();}void onPause(){navView.onPause();}void onStop(){navView.onStop();}void onDestroy(){navView.onDestroy();}void onSave(Bundle b){navView.onSaveInstanceState(b);}
}
