package com.mdiaz.trxlauncher;
import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class ObdService extends Service{
 static volatile boolean connected;static volatile String status="DISCONNECTED",rpm="--",coolant="--",intake="--",voltage="--",load="--";private volatile boolean run;private BluetoothSocket socket;
 @Override public void onCreate(){super.onCreate();createChannel();startForeground(73,new Notification.Builder(this,"trx-obd").setSmallIcon(android.R.drawable.stat_sys_data_bluetooth).setContentTitle("TRX Launcher · OBDLink MX+").setContentText("Connecting to vehicle data").build());run=true;new Thread(this::loop,"trx-obd-mx").start();}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}@Override public android.os.IBinder onBind(Intent i){return null;}@Override public void onDestroy(){run=false;close();super.onDestroy();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("trx-obd","OBDLink MX+ connection",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private void loop(){while(run){try{connectMx();initialize();connected=true;status="OBD READY";while(run&&socket!=null&&socket.isConnected()){rpm=decodeRpm(command("010C"));coolant=decodeTemp(command("0105"));intake=decodeTemp(command("010F"));load=decodePercent(command("0104"));voltage=decodeVoltage(command("0142"));Thread.sleep(450);}}catch(SecurityException e){status="BLUETOOTH PERMISSION REQUIRED";}catch(Throwable e){status="RECONNECTING";}finally{connected=false;close();}try{Thread.sleep(3000);}catch(InterruptedException ignored){}}}
 private void connectMx()throws Exception{status="LOOKING FOR OBDLINK MX+";BluetoothAdapter adapter=BluetoothAdapter.getDefaultAdapter();if(adapter==null||!adapter.isEnabled())throw new IOException("Bluetooth off");if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(android.Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)throw new SecurityException();BluetoothDevice found=null;for(BluetoothDevice d:adapter.getBondedDevices()){String n=d.getName();if(n!=null&&(n.toUpperCase().contains("OBDLINK")||n.toUpperCase().contains("MX+"))){found=d;break;}}if(found==null){status="PAIR OBDLINK MX+ IN SETTINGS";throw new IOException("not paired");}socket=found.createRfcommSocketToServiceRecord(UUID.fromString("00001101-0000-1000-8000-00805F9B34FB"));socket.connect();}
 private void initialize()throws Exception{command("ATZ");command("ATE0");command("ATL0");command("ATS0");command("ATH0");command("ATSP0");}
 private synchronized String command(String cmd)throws Exception{OutputStream out=socket.getOutputStream();InputStream in=socket.getInputStream();out.write((cmd+"\r").getBytes(StandardCharsets.US_ASCII));out.flush();StringBuilder s=new StringBuilder();long end=System.currentTimeMillis()+3500;while(System.currentTimeMillis()<end){if(in.available()>0){int b=in.read();if(b<0)break;if(b=='>')break;s.append((char)b);}else Thread.sleep(10);}return s.toString().replaceAll("[^0-9A-Fa-f]","").toUpperCase();}
 private String payload(String raw,String modePid){int i=raw.lastIndexOf("41"+modePid.substring(2));return i<0?"":raw.substring(i+4);}
 private String decodeRpm(String r){try{String p=payload(r,"010C");return String.valueOf((Integer.parseInt(p.substring(0,2),16)*256+Integer.parseInt(p.substring(2,4),16))/4);}catch(Exception e){return "--";}}
 private String decodeTemp(String r){try{String p=payload(r,r.contains("4105")?"0105":"010F");return String.valueOf(Math.round((Integer.parseInt(p.substring(0,2),16)-40)*9f/5f+32));}catch(Exception e){return "--";}}
 private String decodePercent(String r){try{return String.valueOf(Math.round(Integer.parseInt(payload(r,"0104").substring(0,2),16)*100f/255f));}catch(Exception e){return "--";}}
 private String decodeVoltage(String r){try{String p=payload(r,"0142");return String.format(Locale.US,"%.1f",(Integer.parseInt(p.substring(0,2),16)*256+Integer.parseInt(p.substring(2,4),16))/1000f);}catch(Exception e){return "--";}}
 private void close(){try{if(socket!=null)socket.close();}catch(Throwable ignored){}socket=null;}
}
