package com.mdiaz.trxlauncher;
import android.content.*;import android.graphics.Color;import android.provider.Settings;import android.text.InputType;import android.widget.*;
final class SettingsScreen extends ScrollView{
 private final MainActivity a;private final android.content.SharedPreferences prefs;
 SettingsScreen(MainActivity activity){super(activity);a=activity;prefs=a.getSharedPreferences("trx",0);setFillViewport(true);render();}
 private void render(){removeAllViews();LinearLayout root=Ui.col(a);root.setPadding(24,18,24,24);addView(root);root.addView(Ui.text(a,"TRX LAUNCHER SETTINGS",30,Color.WHITE,true));root.addView(Ui.text(a,"Version 5.2.0  •  Precision cockpit configuration",13,0xffa5a8ae,false));add(root,"Appearance & Theme","TRX Red, Baja Amber, Electric Blue, or Stealth Silver",this::themePicker);add(root,"Navigation","Traffic, camera, route preferences and guidance audio",this::navigationSettings);add(root,"Media Controls","Basic controls work without special access",this::mediaSettings);add(root,"OBD-II / OBDLink MX+","Pair the adapter and manage automatic reconnect",()->open(Settings.ACTION_BLUETOOTH_SETTINGS));add(root,"Home & Work","Save full addresses for one-tap routes",this::homeWork);add(root,"Quick Launch","Configure the Home and Apps launch rails",()->Toast.makeText(a,"Hold an app tile to add or remove Quick Launch",Toast.LENGTH_LONG).show());add(root,"Audio","Open Android output and volume controls",()->open(Settings.ACTION_SOUND_SETTINGS));add(root,"App Permissions","Location only for Navigation; Bluetooth only for Performance",()->open(Settings.ACTION_APPLICATION_DETAILS_SETTINGS));add(root,"Backup & Reset","Clear launcher preferences without removing Bluetooth pairings",this::reset);add(root,"About TRX Launcher 5","Build 120 • Navigation SDK • OBDLink MX+",()->new android.app.AlertDialog.Builder(a).setTitle("TRX Launcher 5.2.0").setMessage("RAM TRX precision cockpit\n\nGoogle Navigation SDK 7.9\nGoogle Places autocomplete\nOBDLink MX+ standard PID service\nOptional MediaSession metadata").setPositiveButton("Done",null).show());}
 private void add(LinearLayout root,String title,String subtitle,Runnable action){Button b=Ui.button(a,title+"\n"+subtitle,false);b.setGravity(android.view.Gravity.LEFT|android.view.Gravity.CENTER_VERTICAL);b.setPadding(24,4,18,4);b.setOnClickListener(v->action.run());root.addView(b,new LinearLayout.LayoutParams(-1,86));Ui.margins(b,0,6,0,6);}
 private void themePicker(){new android.app.AlertDialog.Builder(a).setTitle("Choose cockpit theme").setSingleChoiceItems(ThemeStore.NAMES,prefs.getInt("theme",0),(d,w)->{ThemeStore.set(a,w);d.dismiss();a.recreate();}).setNegativeButton("Cancel",null).show();}
 private void navigationSettings(){String[] keys={"traffic","follow3d","voice","avoid_tolls","avoid_highways","avoid_ferries","hybrid"};String[] labels={"Live traffic","3D follow camera","Voice guidance","Avoid tolls","Avoid highways","Avoid ferries","Satellite / hybrid layer"};boolean[] values={prefs.getBoolean(keys[0],true),prefs.getBoolean(keys[1],true),prefs.getBoolean(keys[2],true),prefs.getBoolean(keys[3],false),prefs.getBoolean(keys[4],false),prefs.getBoolean(keys[5],false),prefs.getBoolean(keys[6],false)};new android.app.AlertDialog.Builder(a).setTitle("Navigation preferences").setMultiChoiceItems(labels,values,(d,w,on)->prefs.edit().putBoolean(keys[w],on).apply()).setPositiveButton("Done",null).show();}
 private void mediaSettings(){new android.app.AlertDialog.Builder(a).setTitle("Media controls").setMessage("Play, pause, previous and next work without special access. Optional Notification Access adds title, artist, artwork and queue information from the active media app.").setNegativeButton("Basic controls only",null).setPositiveButton("Enable metadata",(d,w)->a.requestMediaAccess()).show();}
 private void homeWork(){LinearLayout box=Ui.col(a);EditText home=input("Home address",prefs.getString("home",""));EditText work=input("Work address",prefs.getString("work",""));box.setPadding(32,0,32,0);box.addView(home);box.addView(work);new android.app.AlertDialog.Builder(a).setTitle("Home & Work").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->prefs.edit().putString("home",home.getText().toString().trim()).putString("work",work.getText().toString().trim()).apply()).show();}
 private EditText input(String hint,String value){EditText e=new EditText(a);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_POSTAL_ADDRESS);return e;}
 private void reset(){new android.app.AlertDialog.Builder(a).setTitle("Reset TRX Launcher?").setMessage("Clears themes, saved destinations, favorites and navigation preferences. Android Bluetooth pairings remain intact.").setNegativeButton("Cancel",null).setPositiveButton("Reset",(d,w)->{prefs.edit().clear().apply();a.recreate();}).show();}
 private void open(String action){try{Intent i=new Intent(action);if(action.equals(Settings.ACTION_APPLICATION_DETAILS_SETTINGS))i.setData(android.net.Uri.parse("package:"+a.getPackageName()));a.startActivity(i);}catch(Throwable e){Toast.makeText(a,"Setting unavailable on this device",Toast.LENGTH_SHORT).show();}}
}
